const getHtml = require("../getHtml")

const cookies = [
    {
      name: '_gid',
      value: 'GA1.2.964615025.1650723976',
      domain: '.bongamodels.com',
      path: '/',
      expires: 1650810375,
      size: 30,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'reg_ver2',
      value: '3',
      domain: '.bongamodels.com',
      path: '/',
      expires: 1682259969.948697,
      size: 9,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: '_ga',
      value: 'GA1.2.386173001.1650723976',
      domain: '.bongamodels.com',
      path: '/',
      expires: 1713795975,
      size: 29,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'fv',
      value: 'Zmt5ZmV3ZQH2ZD==',
      domain: '.bongamodels.com',
      path: '/',
      expires: 1682259969.948555,
      size: 18,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'uh',
      value: 'DmOkZRIXDwq0raD3GIO+DxgZFyudpD==',
      domain: '.bongamodels.com',
      path: '/',
      expires: 1682259969.948598,
      size: 34,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'BONGA_REF',
      value: 'https%3A%2F%2Frt.bongacams25.com%2F',
      domain: '.bongamodels.com',
      path: '/',
      expires: 1666275969.948648,
      size: 44,
      httpOnly: true,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: '_gat_gtag_UA_10874655_43',
      value: '1',
      domain: '.bongamodels.com',
      path: '/',
      expires: 1650724035,
      size: 25,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'warning18',
      value: '%5B%22ru_RU%22%5D',
      domain: '.bongamodels.com',
      path: '/',
      expires: 1682259969.948754,
      size: 26,
      httpOnly: false,
      secure: true,
      session: false,
      sameSite: 'None',
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'ts_type2',
      value: '1',
      domain: '.bongamodels.com',
      path: '/',
      expires: 1682259976.365541,
      size: 9,
      httpOnly: false,
      secure: true,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'bonga20120608',
      value: 'dc751dcb56a846de10140ac134493998',
      domain: '.bongamodels.com',
      path: '/',
      expires: -1,
      size: 45,
      httpOnly: true,
      secure: true,
      session: true,
      sameSite: 'None',
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    }
  ]

getHtml("https://ru.bongamodels.com/profile/Opel0707",cookies, false, false, false, true)